language: node_js
node_js:
  - "10"
  - "12"

branches:
  only:
    - master

before_script:
  - yarn install

script:
  - yarn build 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  on:
    branch: master
  local_dir: dist/ajsf-demo/
